### ISSUE TITLE
Python Upload file too complicated

### ISSUE THREAD

**Issue by moritzschaefer** [haiwen/webapi-examples#1]
https://github.com/haiwen/webapi-examples/blob/master/python/upload-file.py can be done much more easily with requests:

response = requests.post(uploadlink,
                         data={'filename': filename, 'parent_dir': '/'},
                         files={'file': open(filename, 'rb')},
                         headers={'Authorization': 'Token {token}'.
                                  format(token=token)}
                         )

Adding it as an example in the file would be nice.

**Comment by xiez** [comment]
Thanks! It's done. https://github.com/haiwen/webapi-examples/blob/master/python/upload-file2.py
